
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INTLIT\nProgram : ID ID '(' ')' '{' Declarations Statements '}'\n\nDeclarations : Declarations Declaration\n             | Declaration\n\nDeclaration : ID ID ';'\n\nStatements : Statements Statement\n           | Statement\n\nStatement : Assignment\n\nAssignment : ID '=' Expression ';'\n\nExpression : Expression '+' Term\n           | Expression '-' Term\n           | Term\n\nTerm : Term '*' Factor\n     | Term '/' Factor\n     | Term '%' Factor\n     | Factor\n\nFactor : INTLIT\n       | '(' Expression ')'\n"
    
_lr_action_items = {'ID':([0,2,6,7,8,9,11,12,13,14,15,16,20,26,],[2,3,7,10,11,-3,10,18,-2,-6,-7,-4,-5,-8,]),'$end':([1,19,],[0,-1,]),'(':([3,17,25,27,28,29,30,31,],[4,25,25,25,25,25,25,25,]),')':([4,22,23,24,32,33,34,35,36,37,38,],[5,-11,-15,-16,38,-9,-10,-12,-13,-14,-17,]),'{':([5,],[6,]),';':([10,21,22,23,24,33,34,35,36,37,38,],[16,26,-11,-15,-16,-9,-10,-12,-13,-14,-17,]),'=':([11,18,],[17,17,]),'}':([12,14,15,20,26,],[19,-6,-7,-5,-8,]),'INTLIT':([17,25,27,28,29,30,31,],[24,24,24,24,24,24,24,]),'+':([21,22,23,24,32,33,34,35,36,37,38,],[27,-11,-15,-16,27,-9,-10,-12,-13,-14,-17,]),'-':([21,22,23,24,32,33,34,35,36,37,38,],[28,-11,-15,-16,28,-9,-10,-12,-13,-14,-17,]),'*':([22,23,24,33,34,35,36,37,38,],[29,-15,-16,29,29,-12,-13,-14,-17,]),'/':([22,23,24,33,34,35,36,37,38,],[30,-15,-16,30,30,-12,-13,-14,-17,]),'%':([22,23,24,33,34,35,36,37,38,],[31,-15,-16,31,31,-12,-13,-14,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Program':([0,],[1,]),'Declarations':([6,],[8,]),'Declaration':([6,8,],[9,13,]),'Statements':([8,],[12,]),'Statement':([8,12,],[14,20,]),'Assignment':([8,12,],[15,15,]),'Expression':([17,25,],[21,32,]),'Term':([17,25,27,28,],[22,22,33,34,]),'Factor':([17,25,27,28,29,30,31,],[23,23,23,23,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Program","S'",1,None,None,None),
  ('Program -> ID ID ( ) { Declarations Statements }','Program',8,'p_Program','analisis.py',29),
  ('Declarations -> Declarations Declaration','Declarations',2,'p_Declarations','analisis.py',35),
  ('Declarations -> Declaration','Declarations',1,'p_Declarations','analisis.py',36),
  ('Declaration -> ID ID ;','Declaration',3,'p_Declaration','analisis.py',45),
  ('Statements -> Statements Statement','Statements',2,'p_Statements','analisis.py',51),
  ('Statements -> Statement','Statements',1,'p_Statements','analisis.py',52),
  ('Statement -> Assignment','Statement',1,'p_Statement','analisis.py',61),
  ('Assignment -> ID = Expression ;','Assignment',4,'p_Assignment','analisis.py',67),
  ('Expression -> Expression + Term','Expression',3,'p_Expression','analisis.py',73),
  ('Expression -> Expression - Term','Expression',3,'p_Expression','analisis.py',74),
  ('Expression -> Term','Expression',1,'p_Expression','analisis.py',75),
  ('Term -> Term * Factor','Term',3,'p_Term','analisis.py',84),
  ('Term -> Term / Factor','Term',3,'p_Term','analisis.py',85),
  ('Term -> Term % Factor','Term',3,'p_Term','analisis.py',86),
  ('Term -> Factor','Term',1,'p_Term','analisis.py',87),
  ('Factor -> INTLIT','Factor',1,'p_Factor','analisis.py',96),
  ('Factor -> ( Expression )','Factor',3,'p_Factor','analisis.py',97),
]
